import type { Workflow, ExecutionLog, Integration, Template } from "./types";

export const MOCK_WORKFLOWS: Workflow[] = [
  {
    id: "wf-001",
    name: "Lead Calificación + WhatsApp",
    description: "Clasifica leads entrantes con IA y envía WhatsApp personalizado al equipo de ventas",
    status: "active",
    nodes: [
      { id: "n1", type: "webhook", category: "trigger", label: "Webhook", description: "Recibe leads", icon: "Globe", color: "#6366f1", position: { x: 100, y: 200 }, config: { method: "POST", path: "/lead" } },
      { id: "n2", type: "ai-classifier", category: "ai", label: "AI Classifier", description: "Clasifica el lead", icon: "Tags", color: "#9333ea", position: { x: 350, y: 200 }, config: { categories: "lead_caliente,lead_frio,spam" } },
      { id: "n3", type: "if-condition", category: "logic", label: "IF Condition", description: "Si es caliente", icon: "GitBranch", color: "#b91c1c", position: { x: 600, y: 200 }, config: { field: "{{classification}}", operator: "equals", value: "lead_caliente" } },
      { id: "n4", type: "send-whatsapp", category: "action", label: "Send WhatsApp", description: "Notifica a ventas", icon: "MessageSquare", color: "#15803d", position: { x: 850, y: 100 }, config: { to: "+52 55 1234 5678", message: "¡Nuevo lead caliente! {{nombre}}" } },
      { id: "n5", type: "save-to-crm", category: "action", label: "Save to CRM", description: "Guarda en HubSpot", icon: "Users", color: "#b45309", position: { x: 850, y: 300 }, config: { crmType: "hubspot", entity: "lead" } },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n2" },
      { id: "e2", source: "n2", target: "n3" },
      { id: "e3", source: "n3", target: "n4" },
      { id: "e4", source: "n3", target: "n5" },
    ],
    createdAt: "2026-05-10T14:30:00Z",
    updatedAt: "2026-05-17T09:15:00Z",
    lastExecutedAt: "2026-05-18T08:45:00Z",
    executionCount: 247,
    tags: ["leads", "ventas", "whatsapp"],
  },
  {
    id: "wf-002",
    name: "Resumen Diario de Ventas",
    description: "Genera y envía reporte de ventas por email cada mañana a las 9am",
    status: "active",
    nodes: [
      { id: "n1", type: "schedule", category: "trigger", label: "Schedule", description: "Cada día a las 9am", icon: "Clock", color: "#0891b2", position: { x: 100, y: 200 }, config: { cron: "0 9 * * 1-5" } },
      { id: "n2", type: "database-query", category: "action", label: "DB Query", description: "Consulta ventas", icon: "Database", color: "#1e40af", position: { x: 350, y: 200 }, config: { dbType: "postgresql", query: "SELECT * FROM sales WHERE date = CURRENT_DATE" } },
      { id: "n3", type: "ai-summarizer", category: "ai", label: "AI Summarizer", description: "Resume los datos", icon: "AlignLeft", color: "#7c3aed", position: { x: 600, y: 200 }, config: { maxLength: "500", style: "bullets" } },
      { id: "n4", type: "send-email", category: "action", label: "Send Email", description: "Envía el reporte", icon: "Mail", color: "#0f766e", position: { x: 850, y: 200 }, config: { to: "director@empresa.com", subject: "Resumen de ventas - {{fecha}}" } },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n2" },
      { id: "e2", source: "n2", target: "n3" },
      { id: "e3", source: "n3", target: "n4" },
    ],
    createdAt: "2026-05-05T10:00:00Z",
    updatedAt: "2026-05-16T11:30:00Z",
    lastExecutedAt: "2026-05-18T09:00:00Z",
    executionCount: 13,
    tags: ["ventas", "reportes", "email"],
  },
  {
    id: "wf-003",
    name: "Soporte IA 24/7",
    description: "Responde consultas de soporte con IA, escala si es necesario",
    status: "active",
    nodes: [
      { id: "n1", type: "webhook", category: "trigger", label: "Webhook", description: "Mensaje entrante", icon: "Globe", color: "#6366f1", position: { x: 100, y: 200 }, config: { method: "POST", path: "/support" } },
      { id: "n2", type: "ai-agent", category: "ai", label: "AI Agent", description: "Responde con IA", icon: "Bot", color: "#4f46e5", position: { x: 350, y: 200 }, config: { model: "gpt-4o" } },
      { id: "n3", type: "send-whatsapp", category: "action", label: "WhatsApp", description: "Responde al cliente", icon: "MessageSquare", color: "#15803d", position: { x: 600, y: 200 }, config: { to: "{{from}}", message: "{{aiResponse}}" } },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n2" },
      { id: "e2", source: "n2", target: "n3" },
    ],
    createdAt: "2026-05-12T16:00:00Z",
    updatedAt: "2026-05-18T07:00:00Z",
    lastExecutedAt: "2026-05-18T10:22:00Z",
    executionCount: 1834,
    tags: ["soporte", "ia", "whatsapp"],
  },
  {
    id: "wf-004",
    name: "Validación de Comprobantes",
    description: "Extrae datos de comprobantes de pago con IA y los valida",
    status: "inactive",
    nodes: [
      { id: "n1", type: "form-submission", category: "trigger", label: "Form Submit", description: "Comprobante recibido", icon: "FileText", color: "#059669", position: { x: 100, y: 200 }, config: { formId: "payment_form" } },
      { id: "n2", type: "ai-json-extractor", category: "ai", label: "AI Extractor", description: "Extrae datos del PDF", icon: "Braces", color: "#6d28d9", position: { x: 350, y: 200 }, config: { schema: '{"amount":"","date":"","reference":""}' } },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n2" },
    ],
    createdAt: "2026-05-01T09:00:00Z",
    updatedAt: "2026-05-14T14:00:00Z",
    executionCount: 89,
    tags: ["pagos", "validacion", "ia"],
  },
  {
    id: "wf-005",
    name: "API Automation Hub",
    description: "Orquesta múltiples APIs externas en un solo flujo automatizado",
    status: "draft",
    nodes: [
      { id: "n1", type: "webhook", category: "trigger", label: "Webhook", description: "Petición entrante", icon: "Globe", color: "#6366f1", position: { x: 100, y: 200 }, config: { method: "POST" } },
      { id: "n2", type: "http-request", category: "action", label: "HTTP Request", description: "Consulta API externa", icon: "Zap", color: "#0369a1", position: { x: 350, y: 200 }, config: { url: "https://api.example.com/data", method: "GET" } },
      { id: "n3", type: "transform-data", category: "logic", label: "Transform", description: "Transforma datos", icon: "Shuffle", color: "#0891b2", position: { x: 600, y: 200 }, config: { mode: "merge" } },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n2" },
      { id: "e2", source: "n2", target: "n3" },
    ],
    createdAt: "2026-05-17T11:00:00Z",
    updatedAt: "2026-05-17T11:00:00Z",
    executionCount: 0,
    tags: ["api", "integracion"],
  },
];

export const MOCK_EXECUTION_LOGS: ExecutionLog[] = [
  {
    id: "exec-001",
    workflowId: "wf-001",
    workflowName: "Lead Calificación + WhatsApp",
    startedAt: "2026-05-18T08:45:00Z",
    finishedAt: "2026-05-18T08:45:03Z",
    status: "success",
    duration: 3200,
    steps: [
      { nodeId: "n1", nodeLabel: "Webhook", status: "success", message: "Petición recibida correctamente", timestamp: "2026-05-18T08:45:00Z" },
      { nodeId: "n2", nodeLabel: "AI Classifier", status: "success", message: "Cliente clasificado como lead_caliente (92% confianza)", timestamp: "2026-05-18T08:45:01Z" },
      { nodeId: "n3", nodeLabel: "IF Condition", status: "success", message: "Condición verdadera: lead_caliente === lead_caliente", timestamp: "2026-05-18T08:45:02Z" },
      { nodeId: "n4", nodeLabel: "Send WhatsApp", status: "success", message: "Mensaje enviado a +52 55 1234 5678", timestamp: "2026-05-18T08:45:02Z" },
      { nodeId: "n5", nodeLabel: "Save to CRM", status: "success", message: "Lead guardado en HubSpot (ID: hs_1847362)", timestamp: "2026-05-18T08:45:03Z" },
    ],
  },
  {
    id: "exec-002",
    workflowId: "wf-002",
    workflowName: "Resumen Diario de Ventas",
    startedAt: "2026-05-18T09:00:00Z",
    finishedAt: "2026-05-18T09:00:08Z",
    status: "success",
    duration: 8100,
    steps: [
      { nodeId: "n1", nodeLabel: "Schedule", status: "success", message: "Cron ejecutado a las 09:00", timestamp: "2026-05-18T09:00:00Z" },
      { nodeId: "n2", nodeLabel: "DB Query", status: "success", message: "148 registros de ventas recuperados", timestamp: "2026-05-18T09:00:02Z" },
      { nodeId: "n3", nodeLabel: "AI Summarizer", status: "success", message: "Resumen generado en 3.2s", timestamp: "2026-05-18T09:00:06Z" },
      { nodeId: "n4", nodeLabel: "Send Email", status: "success", message: "Email enviado a director@empresa.com", timestamp: "2026-05-18T09:00:08Z" },
    ],
  },
  {
    id: "exec-003",
    workflowId: "wf-001",
    workflowName: "Lead Calificación + WhatsApp",
    startedAt: "2026-05-18T10:12:00Z",
    finishedAt: "2026-05-18T10:12:05Z",
    status: "error",
    duration: 5000,
    steps: [
      { nodeId: "n1", nodeLabel: "Webhook", status: "success", message: "Petición recibida correctamente", timestamp: "2026-05-18T10:12:00Z" },
      { nodeId: "n2", nodeLabel: "AI Classifier", status: "success", message: "Cliente clasificado como lead_frio", timestamp: "2026-05-18T10:12:02Z" },
      { nodeId: "n3", nodeLabel: "IF Condition", status: "success", message: "Condición falsa: lead_frio !== lead_caliente", timestamp: "2026-05-18T10:12:03Z" },
      { nodeId: "n5", nodeLabel: "Save to CRM", status: "error", message: "Error: CRM API timeout después de 2000ms", timestamp: "2026-05-18T10:12:05Z" },
    ],
  },
];

export const MOCK_INTEGRATIONS: Integration[] = [
  { id: "openai", name: "OpenAI / OpenRouter", status: "connected", icon: "Sparkles", color: "#10b981" },
  { id: "whatsapp", name: "WhatsApp Business", status: "connected", icon: "MessageSquare", color: "#22c55e" },
  { id: "hubspot", name: "HubSpot CRM", status: "connected", icon: "Users", color: "#f97316" },
  { id: "smtp", name: "Email SMTP", status: "disconnected", icon: "Mail", color: "#94a3b8" },
  { id: "sheets", name: "Google Sheets", status: "disconnected", icon: "Table", color: "#94a3b8" },
  { id: "postgres", name: "PostgreSQL", status: "connected", icon: "Database", color: "#3b82f6" },
];

export const MOCK_TEMPLATES: Template[] = [
  {
    id: "tpl-001",
    name: "Lead por Formulario + IA + WhatsApp",
    description: "Captura leads de formulario web, los clasifica con IA y notifica al equipo de ventas via WhatsApp",
    category: "Ventas",
    tags: ["leads", "ia", "whatsapp", "crm"],
    nodeCount: 5,
    icon: "UserPlus",
    color: "#7c3aed",
    workflow: {
      name: "Lead por Formulario + IA + WhatsApp",
      description: "Captura leads de formulario web, los clasifica con IA y notifica al equipo de ventas via WhatsApp",
      status: "draft",
      nodes: [
        { id: "n1", type: "form-submission", category: "trigger", label: "Form Submit", description: "", icon: "FileText", color: "#059669", position: { x: 100, y: 200 }, config: {} },
        { id: "n2", type: "ai-classifier", category: "ai", label: "AI Classifier", description: "", icon: "Tags", color: "#9333ea", position: { x: 350, y: 200 }, config: { categories: "lead_caliente,lead_frio,spam" } },
        { id: "n3", type: "if-condition", category: "logic", label: "IF Condition", description: "", icon: "GitBranch", color: "#b91c1c", position: { x: 600, y: 200 }, config: { field: "{{classification}}", operator: "equals", value: "lead_caliente" } },
        { id: "n4", type: "send-whatsapp", category: "action", label: "Send WhatsApp", description: "", icon: "MessageSquare", color: "#15803d", position: { x: 850, y: 100 }, config: {} },
        { id: "n5", type: "save-to-crm", category: "action", label: "Save to CRM", description: "", icon: "Users", color: "#b45309", position: { x: 850, y: 300 }, config: {} },
      ],
      edges: [
        { id: "e1", source: "n1", target: "n2" },
        { id: "e2", source: "n2", target: "n3" },
        { id: "e3", source: "n3", target: "n4" },
        { id: "e4", source: "n3", target: "n5" },
      ],
      tags: ["leads", "ia", "whatsapp", "crm"],
    },
  },
  {
    id: "tpl-002",
    name: "Resumen Diario de Ventas",
    description: "Consulta la BD, resume con IA y envía reporte diario por email al equipo directivo",
    category: "Reportes",
    tags: ["ventas", "reportes", "ia", "email"],
    nodeCount: 4,
    icon: "BarChart2",
    color: "#0369a1",
    workflow: {
      name: "Resumen Diario de Ventas",
      description: "Consulta la BD, resume con IA y envía reporte diario por email",
      status: "draft",
      nodes: [
        { id: "n1", type: "schedule", category: "trigger", label: "Schedule", description: "", icon: "Clock", color: "#0891b2", position: { x: 100, y: 200 }, config: { cron: "0 9 * * 1-5" } },
        { id: "n2", type: "database-query", category: "action", label: "DB Query", description: "", icon: "Database", color: "#1e40af", position: { x: 350, y: 200 }, config: {} },
        { id: "n3", type: "ai-summarizer", category: "ai", label: "AI Summarizer", description: "", icon: "AlignLeft", color: "#7c3aed", position: { x: 600, y: 200 }, config: {} },
        { id: "n4", type: "send-email", category: "action", label: "Send Email", description: "", icon: "Mail", color: "#0f766e", position: { x: 850, y: 200 }, config: {} },
      ],
      edges: [
        { id: "e1", source: "n1", target: "n2" },
        { id: "e2", source: "n2", target: "n3" },
        { id: "e3", source: "n3", target: "n4" },
      ],
      tags: ["ventas", "reportes"],
    },
  },
  {
    id: "tpl-003",
    name: "Validación de Comprobante de Pago",
    description: "Recibe comprobantes, extrae datos con IA, valida y registra en el sistema contable",
    category: "Finanzas",
    tags: ["pagos", "ia", "contabilidad", "validacion"],
    nodeCount: 4,
    icon: "Receipt",
    color: "#059669",
    workflow: {
      name: "Validación de Comprobante",
      description: "Recibe y valida comprobantes de pago con IA",
      status: "draft",
      nodes: [
        { id: "n1", type: "form-submission", category: "trigger", label: "Form Submit", description: "", icon: "FileText", color: "#059669", position: { x: 100, y: 200 }, config: {} },
        { id: "n2", type: "ai-json-extractor", category: "ai", label: "AI Extractor", description: "", icon: "Braces", color: "#6d28d9", position: { x: 350, y: 200 }, config: {} },
        { id: "n3", type: "if-condition", category: "logic", label: "IF Valid", description: "", icon: "GitBranch", color: "#b91c1c", position: { x: 600, y: 200 }, config: {} },
        { id: "n4", type: "database-query", category: "action", label: "Save Record", description: "", icon: "Database", color: "#1e40af", position: { x: 850, y: 200 }, config: {} },
      ],
      edges: [
        { id: "e1", source: "n1", target: "n2" },
        { id: "e2", source: "n2", target: "n3" },
        { id: "e3", source: "n3", target: "n4" },
      ],
      tags: ["pagos", "validacion"],
    },
  },
  {
    id: "tpl-004",
    name: "Soporte Automático con IA",
    description: "Agente IA que responde consultas de soporte 24/7, con escalación automática a humano",
    category: "Soporte",
    tags: ["soporte", "ia", "agente", "whatsapp"],
    nodeCount: 4,
    icon: "HeadphonesIcon",
    color: "#9333ea",
    workflow: {
      name: "Soporte Automático con IA",
      description: "Agente IA de soporte 24/7 con escalación",
      status: "draft",
      nodes: [
        { id: "n1", type: "webhook", category: "trigger", label: "Webhook", description: "", icon: "Globe", color: "#6366f1", position: { x: 100, y: 200 }, config: {} },
        { id: "n2", type: "ai-agent", category: "ai", label: "AI Agent", description: "", icon: "Bot", color: "#4f46e5", position: { x: 350, y: 200 }, config: { model: "gpt-4o" } },
        { id: "n3", type: "if-condition", category: "logic", label: "Need Human?", description: "", icon: "GitBranch", color: "#b91c1c", position: { x: 600, y: 200 }, config: {} },
        { id: "n4", type: "send-whatsapp", category: "action", label: "WhatsApp", description: "", icon: "MessageSquare", color: "#15803d", position: { x: 850, y: 200 }, config: {} },
      ],
      edges: [
        { id: "e1", source: "n1", target: "n2" },
        { id: "e2", source: "n2", target: "n3" },
        { id: "e3", source: "n3", target: "n4" },
      ],
      tags: ["soporte", "ia"],
    },
  },
  {
    id: "tpl-005",
    name: "Notificación de Inventario Bajo",
    description: "Monitorea inventario en BD, alerta por WhatsApp y email cuando hay stock crítico",
    category: "Operaciones",
    tags: ["inventario", "alertas", "email", "whatsapp"],
    nodeCount: 5,
    icon: "Package",
    color: "#b45309",
    workflow: {
      name: "Notificación de Inventario Bajo",
      description: "Alerta automática de stock crítico",
      status: "draft",
      nodes: [
        { id: "n1", type: "schedule", category: "trigger", label: "Schedule", description: "", icon: "Clock", color: "#0891b2", position: { x: 100, y: 200 }, config: { cron: "0 * * * *" } },
        { id: "n2", type: "database-query", category: "action", label: "Check Stock", description: "", icon: "Database", color: "#1e40af", position: { x: 350, y: 200 }, config: {} },
        { id: "n3", type: "if-condition", category: "logic", label: "Low Stock?", description: "", icon: "GitBranch", color: "#b91c1c", position: { x: 600, y: 200 }, config: {} },
        { id: "n4", type: "send-email", category: "action", label: "Email Alert", description: "", icon: "Mail", color: "#0f766e", position: { x: 850, y: 100 }, config: {} },
        { id: "n5", type: "send-whatsapp", category: "action", label: "WhatsApp Alert", description: "", icon: "MessageSquare", color: "#15803d", position: { x: 850, y: 300 }, config: {} },
      ],
      edges: [
        { id: "e1", source: "n1", target: "n2" },
        { id: "e2", source: "n2", target: "n3" },
        { id: "e3", source: "n3", target: "n4" },
        { id: "e4", source: "n3", target: "n5" },
      ],
      tags: ["inventario", "alertas"],
    },
  },
  {
    id: "tpl-grok-support",
    name: "Soporte Automático con Grok",
    description: "Webhook recibe mensaje del cliente → Grok AI genera respuesta inteligente → WhatsApp envía la respuesta automáticamente",
    category: "IA",
    tags: ["grok", "xai", "soporte", "whatsapp", "ia"],
    nodeCount: 3,
    icon: "Zap",
    color: "#000000",
    workflow: {
      name: "Soporte Automático con Grok",
      description: "Webhook → Grok Chat → WhatsApp automático",
      status: "draft",
      nodes: [
        {
          id: "n1",
          type: "webhook",
          category: "trigger",
          label: "Webhook",
          description: "Recibe mensaje del cliente",
          icon: "Globe",
          color: "#6366f1",
          position: { x: 100, y: 200 },
          config: { method: "POST", path: "/support" },
        },
        {
          id: "n2",
          type: "grok-chat",
          category: "ai",
          label: "Grok Chat",
          description: "Genera respuesta con Grok AI",
          icon: "Zap",
          color: "#000000",
          position: { x: 400, y: 200 },
          config: {
            model: "grok-3-mini",
            provider: "grok",
            maxTokens: "500",
            temperature: "0.7",
            systemPrompt: "Eres un agente de soporte amigable y eficiente. Responde de forma clara y concisa.",
            prompt: "{{message}}",
          },
        },
        {
          id: "n3",
          type: "send-whatsapp",
          category: "action",
          label: "Send WhatsApp",
          description: "Envía respuesta al cliente",
          icon: "MessageSquare",
          color: "#15803d",
          position: { x: 700, y: 200 },
          config: { to: "{{from}}", message: "{{response}}" },
        },
      ],
      edges: [
        { id: "e1", source: "n1", target: "n2" },
        { id: "e2", source: "n2", target: "n3" },
      ],
      tags: ["grok", "soporte", "whatsapp"],
    },
  },
  {
    id: "tpl-006",
    name: "HTTP API Automation",
    description: "Orquesta múltiples APIs externas: recibe webhook, llama APIs, transforma datos y responde",
    category: "Integraciones",
    tags: ["api", "http", "integracion", "datos"],
    nodeCount: 4,
    icon: "Zap",
    color: "#0369a1",
    workflow: {
      name: "HTTP API Automation",
      description: "Orquestación de múltiples APIs",
      status: "draft",
      nodes: [
        { id: "n1", type: "webhook", category: "trigger", label: "Webhook", description: "", icon: "Globe", color: "#6366f1", position: { x: 100, y: 200 }, config: { method: "POST" } },
        { id: "n2", type: "http-request", category: "action", label: "API Call 1", description: "", icon: "Zap", color: "#0369a1", position: { x: 350, y: 200 }, config: { method: "GET" } },
        { id: "n3", type: "transform-data", category: "logic", label: "Transform", description: "", icon: "Shuffle", color: "#0891b2", position: { x: 600, y: 200 }, config: { mode: "merge" } },
        { id: "n4", type: "http-request", category: "action", label: "API Call 2", description: "", icon: "Zap", color: "#0369a1", position: { x: 850, y: 200 }, config: { method: "POST" } },
      ],
      edges: [
        { id: "e1", source: "n1", target: "n2" },
        { id: "e2", source: "n2", target: "n3" },
        { id: "e3", source: "n3", target: "n4" },
      ],
      tags: ["api", "http"],
    },
  },
];
