import type { NodeDefinition } from "./types";

export const NODE_DEFINITIONS: NodeDefinition[] = [
  // TRIGGERS
  {
    type: "manual-trigger",
    category: "trigger",
    label: "Manual Trigger",
    description: "Inicia el flujo manualmente",
    icon: "Play",
    color: "#7c3aed",
    accentColor: "#a855f7",
    defaultConfig: {},
    configFields: [],
  },
  {
    type: "webhook",
    category: "trigger",
    label: "Webhook",
    description: "Recibe peticiones HTTP entrantes",
    icon: "Globe",
    color: "#6366f1",
    accentColor: "#818cf8",
    defaultConfig: { method: "POST", path: "/webhook" },
    configFields: [
      { key: "method", label: "Método HTTP", type: "select", options: [
        { label: "POST", value: "POST" },
        { label: "GET", value: "GET" },
        { label: "PUT", value: "PUT" },
      ]},
      { key: "path", label: "Ruta", type: "text", placeholder: "/webhook" },
    ],
  },
  {
    type: "schedule",
    category: "trigger",
    label: "Schedule / Cron",
    description: "Ejecuta el flujo en horario programado",
    icon: "Clock",
    color: "#0891b2",
    accentColor: "#06b6d4",
    defaultConfig: { cron: "0 9 * * 1-5", timezone: "America/Mexico_City" },
    configFields: [
      { key: "cron", label: "Expresión Cron", type: "text", placeholder: "0 9 * * 1-5" },
      { key: "timezone", label: "Zona horaria", type: "text", placeholder: "America/Mexico_City" },
    ],
  },
  {
    type: "form-submission",
    category: "trigger",
    label: "Form Submission",
    description: "Activado al enviar un formulario",
    icon: "FileText",
    color: "#059669",
    accentColor: "#10b981",
    defaultConfig: { formId: "", source: "web" },
    configFields: [
      { key: "formId", label: "ID del formulario", type: "text", placeholder: "form_001" },
      { key: "source", label: "Fuente", type: "select", options: [
        { label: "Web", value: "web" },
        { label: "Mobile", value: "mobile" },
        { label: "API", value: "api" },
      ]},
    ],
  },
  // AI
  {
    type: "ai-text-generator",
    category: "ai",
    label: "AI Text Generator",
    description: "Genera texto con IA usando un prompt",
    icon: "Sparkles",
    color: "#7c3aed",
    accentColor: "#c084fc",
    defaultConfig: { model: "gpt-4o-mini", prompt: "", maxTokens: "500", temperature: "0.7" },
    configFields: [
      { key: "model", label: "Modelo", type: "select", options: [
        { label: "GPT-4o Mini", value: "gpt-4o-mini" },
        { label: "GPT-4o", value: "gpt-4o" },
        { label: "Claude Sonnet", value: "claude-3-5-sonnet" },
        { label: "Llama 3.3", value: "llama-3.3-70b" },
        { label: "Grok xAI — grok-3-mini free", value: "grok-3-mini" },
        { label: "Grok xAI — grok-3", value: "grok-3" },
      ]},
      { key: "provider", label: "Provider", type: "select", options: [
        { label: "OpenAI", value: "openai" },
        { label: "OpenRouter", value: "openrouter" },
        { label: "Grok — xAI (grok-3-mini free)", value: "grok" },
      ]},
      { key: "prompt", label: "Prompt", type: "textarea", placeholder: "Escribe el prompt aquí..." },
      { key: "maxTokens", label: "Max Tokens", type: "number", placeholder: "500" },
      { key: "temperature", label: "Temperature", type: "number", placeholder: "0.7" },
    ],
  },
  {
    type: "ai-classifier",
    category: "ai",
    label: "AI Classifier",
    description: "Clasifica texto en categorías con IA",
    icon: "Tags",
    color: "#9333ea",
    accentColor: "#d946ef",
    defaultConfig: { categories: "lead_caliente,lead_frio,spam", inputField: "message" },
    configFields: [
      { key: "categories", label: "Categorías (separadas por coma)", type: "text", placeholder: "categoría1,categoría2" },
      { key: "inputField", label: "Campo de entrada", type: "text", placeholder: "message" },
    ],
  },
  {
    type: "ai-summarizer",
    category: "ai",
    label: "AI Summarizer",
    description: "Resume texto largo de forma inteligente",
    icon: "AlignLeft",
    color: "#7c3aed",
    accentColor: "#a78bfa",
    defaultConfig: { maxLength: "200", style: "bullets" },
    configFields: [
      { key: "maxLength", label: "Longitud máxima", type: "number", placeholder: "200" },
      { key: "style", label: "Estilo", type: "select", options: [
        { label: "Párrafo", value: "paragraph" },
        { label: "Bullets", value: "bullets" },
        { label: "JSON", value: "json" },
      ]},
    ],
  },
  {
    type: "ai-json-extractor",
    category: "ai",
    label: "AI JSON Extractor",
    description: "Extrae datos estructurados en JSON",
    icon: "Braces",
    color: "#6d28d9",
    accentColor: "#8b5cf6",
    defaultConfig: { schema: '{"name":"","email":"","phone":""}', inputField: "text" },
    configFields: [
      { key: "schema", label: "Schema JSON", type: "textarea", placeholder: '{"name":"","email":""}' },
      { key: "inputField", label: "Campo de entrada", type: "text", placeholder: "text" },
    ],
  },
  {
    type: "ai-agent",
    category: "ai",
    label: "AI Agent",
    description: "Agente autónomo con herramientas",
    icon: "Bot",
    color: "#4f46e5",
    accentColor: "#818cf8",
    defaultConfig: { model: "gpt-4o", systemPrompt: "Eres un asistente empresarial.", tools: "" },
    configFields: [
      { key: "model", label: "Modelo", type: "select", options: [
        { label: "GPT-4o", value: "gpt-4o" },
        { label: "Claude Opus", value: "claude-3-5-opus" },
        { label: "Grok xAI — grok-3", value: "grok-3" },
        { label: "Grok xAI — grok-3-mini", value: "grok-3-mini" },
      ]},
      { key: "provider", label: "Provider", type: "select", options: [
        { label: "OpenAI", value: "openai" },
        { label: "OpenRouter", value: "openrouter" },
        { label: "Grok — xAI (grok-3-mini free)", value: "grok" },
      ]},
      { key: "systemPrompt", label: "System Prompt", type: "textarea", placeholder: "Eres un asistente..." },
    ],
  },
  // Grok Chat — dedicated node for xAI Grok
  {
    type: "grok-chat",
    category: "ai",
    label: "Grok Chat",
    description: "Conversacional con Grok AI de xAI",
    icon: "Zap",
    color: "#000000",
    accentColor: "#1a1a1a",
    defaultConfig: {
      model: "grok-3-mini",
      provider: "grok",
      maxTokens: "500",
      temperature: "0.7",
      systemPrompt: "Eres un asistente útil dentro de DeepNode Flow.",
    },
    configFields: [
      { key: "model", label: "Modelo Grok", type: "select", options: [
        { label: "grok-3-mini (rápido · free)", value: "grok-3-mini" },
        { label: "grok-3 (potente)", value: "grok-3" },
        { label: "grok-vision (multimodal)", value: "grok-vision" },
      ]},
      { key: "systemPrompt", label: "System Prompt", type: "textarea", placeholder: "Eres un asistente útil..." },
      { key: "prompt", label: "Prompt / Mensaje", type: "textarea", placeholder: "{{mensaje}} o escribe aquí..." },
      { key: "maxTokens", label: "Max Tokens", type: "number", placeholder: "500" },
      { key: "temperature", label: "Temperature (0–1)", type: "number", placeholder: "0.7" },
    ],
  },
  // ACTIONS
  {
    type: "http-request",
    category: "action",
    label: "HTTP Request",
    description: "Realiza peticiones HTTP a APIs externas",
    icon: "Zap",
    color: "#0369a1",
    accentColor: "#0ea5e9",
    defaultConfig: { url: "", method: "GET", headers: "{}", body: "" },
    configFields: [
      { key: "url", label: "URL", type: "text", placeholder: "https://api.ejemplo.com/endpoint", required: true },
      { key: "method", label: "Método", type: "select", options: [
        { label: "GET", value: "GET" },
        { label: "POST", value: "POST" },
        { label: "PUT", value: "PUT" },
        { label: "DELETE", value: "DELETE" },
        { label: "PATCH", value: "PATCH" },
      ]},
      { key: "headers", label: "Headers (JSON)", type: "textarea", placeholder: '{"Content-Type":"application/json"}' },
      { key: "body", label: "Body", type: "textarea", placeholder: '{"key":"value"}' },
    ],
  },
  {
    type: "send-email",
    category: "action",
    label: "Send Email",
    description: "Envía un correo electrónico",
    icon: "Mail",
    color: "#0f766e",
    accentColor: "#14b8a6",
    defaultConfig: { to: "", subject: "", body: "", from: "" },
    configFields: [
      { key: "to", label: "Para (To)", type: "text", placeholder: "cliente@empresa.com", required: true },
      { key: "subject", label: "Asunto", type: "text", placeholder: "Tu solicitud fue procesada", required: true },
      { key: "body", label: "Cuerpo del email", type: "textarea", placeholder: "Hola {{nombre}},..." },
      { key: "from", label: "De (From)", type: "text", placeholder: "no-reply@tuempresa.com" },
    ],
  },
  {
    type: "send-whatsapp",
    category: "action",
    label: "Send WhatsApp",
    description: "Envía mensaje por WhatsApp Business",
    icon: "MessageSquare",
    color: "#15803d",
    accentColor: "#22c55e",
    defaultConfig: { to: "", message: "", template: "" },
    configFields: [
      { key: "to", label: "Número de teléfono", type: "text", placeholder: "+52 55 1234 5678", required: true },
      { key: "message", label: "Mensaje", type: "textarea", placeholder: "Hola {{nombre}}, tu pedido está listo..." },
      { key: "template", label: "Template ID (opcional)", type: "text", placeholder: "hello_world" },
    ],
  },
  {
    type: "save-to-crm",
    category: "action",
    label: "Save to CRM",
    description: "Guarda datos en el CRM",
    icon: "Users",
    color: "#b45309",
    accentColor: "#f59e0b",
    defaultConfig: { crmType: "hubspot", entity: "contact", data: "{}" },
    configFields: [
      { key: "crmType", label: "CRM", type: "select", options: [
        { label: "HubSpot", value: "hubspot" },
        { label: "Salesforce", value: "salesforce" },
        { label: "Zoho", value: "zoho" },
        { label: "Pipedrive", value: "pipedrive" },
      ]},
      { key: "entity", label: "Entidad", type: "select", options: [
        { label: "Contacto", value: "contact" },
        { label: "Lead", value: "lead" },
        { label: "Deal", value: "deal" },
      ]},
      { key: "data", label: "Datos (JSON)", type: "textarea", placeholder: '{"firstName":"{{nombre}}"}' },
    ],
  },
  {
    type: "save-to-sheets",
    category: "action",
    label: "Save to Google Sheets",
    description: "Guarda datos en Google Sheets",
    icon: "Table",
    color: "#166534",
    accentColor: "#22c55e",
    defaultConfig: { spreadsheetId: "", sheetName: "Sheet1", values: "[]" },
    configFields: [
      { key: "spreadsheetId", label: "ID del Spreadsheet", type: "text", placeholder: "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgVE2upms" },
      { key: "sheetName", label: "Nombre de la hoja", type: "text", placeholder: "Sheet1" },
      { key: "values", label: "Valores (JSON array)", type: "textarea", placeholder: '["{{nombre}}","{{email}}"]' },
    ],
  },
  {
    type: "database-query",
    category: "action",
    label: "Database Query",
    description: "Ejecuta consultas en base de datos",
    icon: "Database",
    color: "#1e40af",
    accentColor: "#3b82f6",
    defaultConfig: { dbType: "postgresql", query: "", params: "[]" },
    configFields: [
      { key: "dbType", label: "Base de datos", type: "select", options: [
        { label: "PostgreSQL", value: "postgresql" },
        { label: "MySQL", value: "mysql" },
        { label: "MongoDB", value: "mongodb" },
        { label: "Supabase", value: "supabase" },
      ]},
      { key: "query", label: "Query SQL", type: "textarea", placeholder: "SELECT * FROM users WHERE email = $1" },
      { key: "params", label: "Parámetros (JSON)", type: "textarea", placeholder: '["{{email}}"]' },
    ],
  },
  {
    type: "notification",
    category: "action",
    label: "Notification",
    description: "Envía notificación push o en-app",
    icon: "Bell",
    color: "#7e22ce",
    accentColor: "#a855f7",
    defaultConfig: { channel: "push", title: "", body: "", userId: "" },
    configFields: [
      { key: "channel", label: "Canal", type: "select", options: [
        { label: "Push", value: "push" },
        { label: "In-App", value: "in-app" },
        { label: "Slack", value: "slack" },
        { label: "Teams", value: "teams" },
      ]},
      { key: "title", label: "Título", type: "text", placeholder: "¡Acción requerida!" },
      { key: "body", label: "Mensaje", type: "textarea", placeholder: "Tienes un nuevo lead..." },
    ],
  },
  // LOGIC
  {
    type: "if-condition",
    category: "logic",
    label: "IF Condition",
    description: "Bifurca el flujo según una condición",
    icon: "GitBranch",
    color: "#b91c1c",
    accentColor: "#ef4444",
    defaultConfig: { field: "", operator: "equals", value: "" },
    configFields: [
      { key: "field", label: "Campo a evaluar", type: "text", placeholder: "{{status}}" },
      { key: "operator", label: "Operador", type: "select", options: [
        { label: "Es igual a", value: "equals" },
        { label: "No es igual", value: "not_equals" },
        { label: "Contiene", value: "contains" },
        { label: "Mayor que", value: "greater_than" },
        { label: "Menor que", value: "less_than" },
        { label: "Existe", value: "exists" },
      ]},
      { key: "value", label: "Valor", type: "text", placeholder: "lead_caliente" },
    ],
  },
  {
    type: "delay",
    category: "logic",
    label: "Delay",
    description: "Pausa la ejecución por un tiempo",
    icon: "Timer",
    color: "#92400e",
    accentColor: "#f59e0b",
    defaultConfig: { duration: "5", unit: "seconds" },
    configFields: [
      { key: "duration", label: "Duración", type: "number", placeholder: "5" },
      { key: "unit", label: "Unidad", type: "select", options: [
        { label: "Segundos", value: "seconds" },
        { label: "Minutos", value: "minutes" },
        { label: "Horas", value: "hours" },
        { label: "Días", value: "days" },
      ]},
    ],
  },
  {
    type: "loop",
    category: "logic",
    label: "Loop",
    description: "Itera sobre una lista de elementos",
    icon: "RefreshCw",
    color: "#0f766e",
    accentColor: "#14b8a6",
    defaultConfig: { inputArray: "{{items}}", batchSize: "1" },
    configFields: [
      { key: "inputArray", label: "Array de entrada", type: "text", placeholder: "{{items}}" },
      { key: "batchSize", label: "Tamaño de lote", type: "number", placeholder: "1" },
    ],
  },
  {
    type: "transform-data",
    category: "logic",
    label: "Transform Data",
    description: "Transforma y mapea datos del flujo",
    icon: "Shuffle",
    color: "#0891b2",
    accentColor: "#06b6d4",
    defaultConfig: { transformation: "{}", mode: "merge" },
    configFields: [
      { key: "transformation", label: "Transformación (JSON)", type: "textarea", placeholder: '{"newField":"{{oldField}}"}' },
      { key: "mode", label: "Modo", type: "select", options: [
        { label: "Merge", value: "merge" },
        { label: "Replace", value: "replace" },
        { label: "Pick", value: "pick" },
      ]},
    ],
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  trigger: "Triggers",
  ai: "Inteligencia Artificial",
  action: "Acciones",
  logic: "Lógica",
};

export const CATEGORY_COLORS: Record<string, string> = {
  trigger: "#7c3aed",
  ai: "#9333ea",
  action: "#0369a1",
  logic: "#b91c1c",
};

export function getNodeDefinition(type: string): NodeDefinition | undefined {
  return NODE_DEFINITIONS.find((n) => n.type === type);
}
