import type { PricingPlan } from "./types";

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "starter",
    name: "Starter",
    tagline: "Perfecto para explorar la plataforma",
    monthlyPrice: 0,
    annualPrice: 0,
    color: "#6366f1",
    accentColor: "#818cf8",
    limits: {
      workflows: 3,
      executions: 100,
      teamMembers: 1,
    },
    features: [
      { label: "3 Workflows activos", included: true },
      { label: "100 ejecuciones / mes", included: true },
      { label: "Modo Demo (simulación)", included: true },
      { label: "Nodos básicos (Trigger, Webhook, Email)", included: true },
      { label: "Modo Producción", included: false },
      { label: "Nodos AI (Grok, GPT, Claude)", included: false },
      { label: "Telegram + WhatsApp", included: false },
      { label: "Exportar workflows JSON", included: false },
      { label: "Soporte prioritario", included: false },
    ],
  },
  {
    id: "pro",
    name: "Pro",
    tagline: "Para creadores y freelancers",
    monthlyPrice: 29,
    annualPrice: 290,
    color: "#06b6d4",
    accentColor: "#22d3ee",
    popular: true,
    stripePriceMonthly: process.env.NEXT_PUBLIC_STRIPE_PRO_MONTHLY,
    stripePriceAnnual: process.env.NEXT_PUBLIC_STRIPE_PRO_ANNUAL,
    limits: {
      workflows: 20,
      executions: 5000,
      teamMembers: 1,
    },
    features: [
      { label: "20 Workflows activos", included: true },
      { label: "5,000 ejecuciones / mes", included: true },
      { label: "Modo Producción completo", included: true },
      { label: "Nodos AI — Grok, GPT-4o, Claude", included: true },
      { label: "Telegram + Email + WhatsApp", included: true },
      { label: "Exportar workflows JSON", included: true },
      { label: "Analytics básicos", included: true },
      { label: "Soporte prioritario por email", included: true },
      { label: "Equipo / multi-usuario", included: false },
    ],
  },
  {
    id: "business",
    name: "Business",
    tagline: "Para equipos y empresas en crecimiento",
    monthlyPrice: 79,
    annualPrice: 790,
    color: "#a855f7",
    accentColor: "#c084fc",
    stripePriceMonthly: process.env.NEXT_PUBLIC_STRIPE_BUSINESS_MONTHLY,
    stripePriceAnnual: process.env.NEXT_PUBLIC_STRIPE_BUSINESS_ANNUAL,
    limits: {
      workflows: "unlimited",
      executions: 25000,
      teamMembers: 5,
    },
    features: [
      { label: "Workflows ilimitados", included: true },
      { label: "25,000 ejecuciones / mes", included: true },
      { label: "Todo de Pro incluido", included: true },
      { label: "5 miembros del equipo", included: true },
      { label: "Analytics avanzados + reportes", included: true },
      { label: "API Access + Custom Webhooks", included: true },
      { label: "Historial de ejecuciones 90 días", included: true },
      { label: "SLA 99.9% uptime garantizado", included: true },
      { label: "Soporte chat en vivo", included: true },
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    tagline: "Para organizaciones a gran escala",
    monthlyPrice: null,
    annualPrice: null,
    color: "#f59e0b",
    accentColor: "#fbbf24",
    limits: {
      workflows: "unlimited",
      executions: "unlimited",
      teamMembers: "unlimited",
    },
    features: [
      { label: "Todo de Business incluido", included: true },
      { label: "Ejecuciones ilimitadas", included: true },
      { label: "Equipo ilimitado", included: true },
      { label: "On-premise deployment", included: true },
      { label: "SSO / SAML enterprise", included: true },
      { label: "Auditoría y compliance logs", included: true },
      { label: "Integraciones custom", included: true },
      { label: "SLA 99.99% garantizado", included: true },
      { label: "Soporte dedicado 24/7", included: true },
    ],
  },
];

export const PLAN_LIMITS: Record<string, { workflows: number | "unlimited"; executions: number | "unlimited" }> = {
  starter:    { workflows: 3,           executions: 100   },
  pro:        { workflows: 20,          executions: 5000  },
  business:   { workflows: "unlimited", executions: 25000 },
  enterprise: { workflows: "unlimited", executions: "unlimited" },
};
